stages:
  - build
  - test
  - deploy

variables:
  REPOSITORY_NAME: "lvsn/openculturas-container"

build:container:
  only:
    - main
    - tags
  trigger:
    project: openculturas/openculturas-container
    branch: main
